---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:        
    rollme: {{ randAlphaNum 5 | quote }}
  name: {{.Values.deploymentname.metadata.name2}}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.depspec.selector.matchLabels.app2}}
  template:
    metadata:
      annotations:        
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
      {{- include "demo.labels2" . | nindent 8 }}
    spec:
      containers:
        - name: {{.Values.app.container.name2}}
          image: {{.Values.app.container.image2}}
          #imagePullPolicy: {{ .Values.pullPolicy }}
          resources:
          {{- toYaml .Values.app.computerc | nindent 12}}
          ports:
            - containerPort: {{.Values.app.ports.containerPort2}}
          env:
        # Define the environment variable
            - name: {{.Values.configmap.mapkey.varname1}} # Notice that the case is different here
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configmap.mapkey.name}}           # The ConfigMap this value comes from.
                  key: {{.Values.configmap.mapkey.varname1}}   # The key to fetch.
            - name: {{.Values.configmap.mapkey.varname2}} # Notice that the case is different here
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.configmap.mapkey.name}}           # The ConfigMap this value comes from.
                  key: {{.Values.configmap.mapkey.varname2}}   # The key to fetch.
