---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:        
    rollme: {{ randAlphaNum 5 | quote }}
  name: {{.Values.deploymentname.metadata.name3}}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.depspec.selector.matchLabels.app3}}
  template:
    metadata:
      annotations:        
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
      {{- include "demo.labels3" . | nindent 8 }}
    spec:
      containers:
        - name: {{.Values.app.container.name3}}
          image: {{.Values.app.container.image3}}
          #imagePullPolicy: {{ .Values.pullPolicy }}
          resources:
          {{- toYaml .Values.app.computerc | nindent 12}}
          ports:
            - containerPort: {{.Values.app.ports.containerPort3}}
